// entry.gr, a 1:1 of the kernel entry in kernel.s
#bits 16
asm("org 0x9000");
asm("start_entry:");
#include <stdbios.gr>
#include <std16.gr>

BiosSetVideoMode(3);

BiosSetCursor(0x2607);

print_string(&kernel_loaded);
asm("cli");

void print_string(uint16 string_ptr) {
    asm("sti");
    pusha();
    asm("mov si, word[.__vararg_string_ptr]");
    while (1==1) {
        lodsb();
        if (al == 0) {
            break;
        }
        BiosTeletypeOutput(0, 0x07);
    }
    popa();
    return;
}

#include "gdt.gr"

// I'm not proud of this one
asm("%defstr KERNEL_NAME_STR KERNEL_NAME");
asm("%defstr KERNEL_BUILD_DATE_STR KERNEL_BUILD_DATE");
asm("kernel_loaded: db 'Starting Kernel: ', KERNEL_NAME_STR, times (80 - (%strlen(KERNEL_NAME_STR) + 17)) db ' ' \n db 'Build date: ', KERNEL_BUILD_DATE_STR, 0");

::kernel_in::
print_string(&kernel_loaded);
ax = cs;
ds = ax;
ss = ax;
esp = 0x9FC00;
asm("lgdt [gdt_descriptor]");
eax = cr0;
eax = eax | 1;
cr0 = eax;
asm("jmp 0x08:0x9200"); // ? Kernel MUST be loaded at 0x9200, I do not care
asm("times 512 - ($ - start_entry) db 0"); // * yes