#bits 32
#include <std32.gr>

#define NULL 0 // standard practice, it's just more practical
#define TRUE 255
#define FALSE 0

#define VIDEO_MEMORY 0xb8000
#define SCREEN_WIDTH 80
#define SCREEN_HEIGHT 25

#define BLACK          0
#define BLUE           1
#define GREEN          2
#define CYAN           3
#define RED            4
#define PURPLE         5
#define BROWN          6
#define GRAY           7
#define DARK_GRAY      8
#define LIGHT_BLUE     9
#define LIGHT_GREEN    10
#define LIGHT_CYAN     11
#define LIGHT_RED      12
#define LIGHT_PURPLE   13
#define YELLOW         14
#define WHITE          15
#define FOREGROUND     1
#define BACKGROUND     0x10

void setChar(uint8 col, uint8 row, uint8 character, uint8 color) {
    pushad();
    edi = VIDEO_MEMORY;
    ecx = row;
    ecx *= SCREEN_WIDTH;
    eax = col;
    ecx += eax;
    ecx <<= 1;
    edi += ecx;
    ax  ^= ax; // xor ax, ax
    al  = character;
    ah  = color;
    asm("mov word[edi], ax");
    popad();
    return;
}

void clearScreen(uint8 color) {
    pushad();
    edi = VIDEO_MEMORY;
    al = ' ';
    ah = color;
    while (ecx > 0) {
        asm("mov [edi], ax");
        edi += 2;
    }
    popad();
    return;
}

#ifdef KERNEL_USE_STD_PRINT
void print(uint8 x, uint8 y, uint8 color, uint32 string_ptr) {
    pushad();
    esi = x;
    while () {
        lodsb();
        if (al == NULL) {
            break;
        }
        setChar(x, y);
        x += 1;
        esi += 1; // I have no idea why but this looks like it works, I could just have used esi btw
    }
    popad();
    return;
}
#endif

uint8 nibbleToAscii() { // only param is al
    if (al > 9) {
        al += "A";
    } else {
        al += "0";
    }
    return;
}

uint32 byteToDWordString(uint8 bytevalue) { // This is the most direct port of int_to_char I could do
    asm("push eax");
    ax = bytevalue;
    ah = al;
    al >>=4;
    nibbleToAscii(); // it works for the time being ok
    cl = al;
    al = ah;
    al &= 0x0F;
    nibbleToAscii();
    ch = al;
    asm("pop eax");
    return cx;
}